// Generated by https://quicktype.io

export interface Event {
  typeName: string;
  fieldName: string;
  arguments: Arguments;
  identity: Identity;
  source: null;
  request: Request;
  prev: Prev;
}

export interface Arguments {
  input: Input;
}
export interface Input {
  name: string;
  boundingBox: BoundingBox;
}

export interface BoundingBox {
  bottomLeft: CoordinatesGeographic;
  upperRight: CoordinatesGeographic;
}

export interface CoordinatesGeographic {
  longitude: number;
  latitude: number;
}

export interface Identity {
  claims: Claims;
  defaultAuthStrategy: string;
  groups: string[];
  issuer: string;
  sourceIp: string[];
  sub: string;
  username: string;
}

export interface Claims {
  sub: string;
  'cognito:groups': string[];
  email_verified: boolean;
  'custom:schedule': string;
  iss: string;
  'cognito:username': string;
  origin_jti: string;
  aud: string;
  'custom:stores': string;
  event_id: string;
  token_use: string;
  'custom:vtexId': string;
  auth_time: number;
  exp: number;
  iat: number;
  jti: string;
  email: string;
}

export interface Prev {
  result: Result;
}

export interface Result {}

export interface Request {
  headers: { [key: string]: string };
}
